name: dinklebot
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0-360.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0
  flutter_secure_storage: ^4.2.1
  dartz: ^0.10.0
  dio: ^4.0.1
  flutter_hooks: ^0.18.0
  flutter_riverpod: ^1.0.0
  freezed_annotation: ^0.15.0
  webview_flutter: ^2.3.0
  flash: ^2.0.0
  auto_route: ^3.0.0
  http: ^0.13.4
  material_design_icons_flutter: ^5.0.6295

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  freezed: ^0.15.0+1
  auto_route_generator: ^3.0.1
  lint: ^1.7.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/graphics/
